eshop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home_module.urls', namespace='home')),
    path('accounts/', include('account_module.urls', namespace='accounts')),
    path('articles/', include('article_module.urls', namespace='articles')),
    path('contact_us/', include('contact_module.urls', namespace='contact_us')),
    path('products/', include('product_module.urls', namespace='products')),
    path('users/', include('user_panel_module.urls', namespace='users')),
    path('orders/', include('order_module.urls', namespace='orders')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.sites.AdminSite.site_title = "پنل مدیریت"
admin.sites.AdminSite.site_header = "پنل مدیریت"
admin.sites.AdminSite.index_title = "پنل مدیریت"

home_module/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home_page'),
    path('about-us/', views.AboutView.as_view(), name='about_page'),
]

order_module/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('add-to-order/', views.add_product_to_order, name='add_product_to_order'),
    path('request-payment/', views.request_payment, name='request_payment'),
    path('verify-payment/', views.verify_payment, name='verify_payment'),
]

user_panel_module/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.UserPanelDashboardPage.as_view(), name='user_panel_dashboard'),
    path('edit-profile/', views.EditUserProfilePage.as_view(), name='edit_profile_page'),
    path('change-pass/', views.ChangePasswordPage.as_view(), name='change_password_page'),
    path('my-shopping/', views.MyShopping.as_view(), name='user_shopping_page'),
    path('my-shopping-detail/<int:order_id>/', views.my_shopping_detail, name='user_shopping_detail_page'),
    path('user-basket/', views.user_basket, name='user_basket_page'),
    path('remove-order-detail/', views.remove_order_detail, name='remove_order_detail_ajax'),
    path('change-order-detail/', views.change_order_detail_count, name='change_order_detail_count_ajax'),
]

user_panel_module/models.py
from django.db import models

user_panel_module/forms.py
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
from account_module.models import User


class EditProfileModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'avatar', 'address', 'about_user']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'avatar': forms.FileInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'about_user': forms.Textarea(attrs={'class': 'form-control', 'rows': 6, 'id': 'message'}),
        }
        labels = {
            'first_name': 'نام',
            'last_name': 'نام خانوادگی',
            'avatar': 'تصویر پروفایل',
            'address': 'آدرس',
            'about_user': 'درباره شخص',
        }


class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(label='کلمه عبور فعلی', widget=forms.PasswordInput(attrs={'class': 'form-control'}), validators=[validators.MaxLengthValidator(100)])
    password = forms.CharField(label='کلمه عبور', widget=forms.PasswordInput(attrs={'class': 'form-control'}), validators=[validators.MaxLengthValidator(100)])
    confirm_password = forms.CharField(label='تکرار کلمه عبور', widget=forms.PasswordInput(attrs={'class': 'form-control'}), validators=[validators.MaxLengthValidator(100)])

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password == confirm_password:
            return confirm_password
        raise ValidationError('کلمه عبور و تکرار کلمه عبور مغایرت دارند')

user_panel_module/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, JsonResponse, Http404
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import TemplateView, ListView
from account_module.models import User
from order_module.models import Order, OrderDetail
from .forms import EditProfileModelForm, ChangePasswordForm


@method_decorator(login_required, name='dispatch')
class UserPanelDashboardPage(TemplateView):
    template_name = 'user_panel_module/user_panel_dashboard_page.html'


@method_decorator(login_required, name='dispatch')
class EditUserProfilePage(View):
    def get(self, request: HttpRequest):
        current_user = User.objects.filter(id=request.user.id).first()
        edit_form = EditProfileModelForm(instance=current_user)
        context = {'form': edit_form, 'current_user': current_user}
        return render(request, 'user_panel_module/edit_profile_page.html', context)

    def post(self, request: HttpRequest):
        current_user = User.objects.filter(id=request.user.id).first()
        edit_form = EditProfileModelForm(data=request.POST, files=request.FILES, instance=current_user)
        if edit_form.is_valid():
            edit_form.save()
            return redirect(reverse('users:user_panel_dashboard'))
        context = {'form': edit_form, 'current_user': current_user}
        return render(request, 'user_panel_module/edit_profile_page.html', context)


@method_decorator(login_required, name='dispatch')
class ChangePasswordPage(View):
    def get(self, request: HttpRequest):
        form = ChangePasswordForm()
        return render(request, 'user_panel_module/change_password_page.html', {'form': form})

    def post(self, request: HttpRequest):
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            current_user: User = User.objects.filter(id=request.user.id).first()
            if current_user.check_password(form.cleaned_data.get('current_password')):
                current_user.set_password(form.cleaned_data.get('password'))
                current_user.save()
                logout(request)
                return redirect(reverse('accounts:login_page'))
            else:
                form.add_error('password', 'کلمه عبور وارد شده اشتباه می باشد')
        return render(request, 'user_panel_module/change_password_page.html', {'form': form})


@method_decorator(login_required, name='dispatch')
class MyShopping(ListView):
    model = Order
    template_name = 'user_panel_module/user_shopping.html'
    context_object_name = 'orders'

    def get_queryset(self):
        queryset = super().get_queryset()
        request: HttpRequest = self.request
        queryset = queryset.filter(user_id=request.user.id, is_paid=True)
        return queryset


@login_required
def my_shopping_detail(request: HttpRequest, order_id):
    order = Order.objects.prefetch_related('order_details').filter(id=order_id, user_id=request.user.id).first()
    if order is None:
        raise Http404('سبد خرید مورد نظر یافت نشد')
    return render(request, 'user_panel_module/user_shopping_detail.html', {'order': order})


@login_required
def user_basket(request: HttpRequest):
    current_order, created = Order.objects.prefetch_related('order_details').get_or_create(is_paid=False, user_id=request.user.id)
    total_amount = current_order.calculate_total_price()
    context = {'order': current_order, 'sum': total_amount}
    return render(request, 'user_panel_module/user_basket.html', context)


@login_required
def remove_order_detail(request):
    detail_id = request.GET.get('detail_id')
    if detail_id is None:
        context = {'status': 'not_found_detail_id'}
        return JsonResponse(context)
    deleted_count, deleted_dict = OrderDetail.objects.filter(id=detail_id, order__is_paid=False, order__user_id=request.user.id).delete()
    if deleted_count == 0:
        context = {'status': 'detail_not_found'}
        return JsonResponse(context)
    current_order, created = Order.objects.prefetch_related('order_details').get_or_create(is_paid=False, user_id=request.user.id)
    total_amount = current_order.calculate_total_price()
    body = render_to_string(template_name='user_panel_module/user_basket_content.html', context={'order': current_order, 'sum': total_amount})
    context = {'status': 'success', 'body': body}
    return JsonResponse(context)


@login_required
def change_order_detail_count(request: HttpRequest):
    detail_id = request.GET.get('detail_id')
    state = request.GET.get('state')
    if detail_id is None or state is None:
        context = {'status': 'not_found_detail_or_state'}
        return JsonResponse(context)
    order_detail = OrderDetail.objects.filter(id=detail_id, order__user_id=request.user.id, order__is_paid=False).first()
    if order_detail is None:
        context = {'status': 'detail_not_found'}
        return JsonResponse(context)
    if state == 'increase':
        order_detail.count += 1
        order_detail.save()
    elif state == 'decrease':
        if order_detail.count == 1:
            order_detail.delete()
        else:
            order_detail.count -= 1
            order_detail.save()
    else:
        context = {'status': 'state_invalid'}
        return JsonResponse(context)
    current_order, created = Order.objects.prefetch_related('order_details').get_or_create(is_paid=False, user_id=request.user.id)
    total_amount = current_order.calculate_total_price()
    body = render_to_string(template_name='user_panel_module/user_basket_content.html', context={'order': current_order, 'sum': total_amount})
    context = {'status': 'success', 'body': body}
    return JsonResponse(context)


@login_required
def user_panel_menu_component(request: HttpRequest):
    return render(request, 'user_panel_module/components/user_panel_menu_component.html')

user_panel_module/templates/user_panel_module/change_password_page.html
{% extends 'shared/_layout.html' %}
{% load render_partial %}

{% block title %}تغییر کلمه عبور{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                {% render_partial 'user_panel_module.views.user_panel_menu_component' %}
            </div>
            <div class="col-md-8">
                <form method="post" action="{% url 'users:change_password_page' %}" novalidate>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">ثبت</button>
                    <br><br>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

user_panel_module/templates/user_panel_module/edit_profile_page.html
{% extends 'shared/_layout.html' %}
{% load thumbnail %}
{% load render_partial %}

{% block title %}ویرایش اطلاعات کاربری{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <a class="thumbnail">
                    {% if current_user.avatar %}
                        {% thumbnail current_user.avatar "862x398" crop='center' quality=100  as img %}
                            <img class="media-object" src="{{ img.url }}" alt="{{ img.name }}">
                        {% endthumbnail %}
                    {% else %}
                        <img class="media-object" src="/static/images/blog/blog-one.jpg" alt="blog one">
                    {% endif %}
                </a>
                {% render_partial 'user_panel_module.views.user_panel_menu_component' %}
            </div>
            <div class="col-md-8">
                <form method="post" action="{% url 'users:edit_profile_page' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">ثبت</button>
                    <br><br>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

user_panel_module/templates/user_panel_module/user_basket.html
{% extends 'shared/_layout.html' %}
{% load poll_extras %}

{% block title %}سبد خرید{% endblock %}

{% block content %}
    <div id="order-detail-content">
        {% include 'user_panel_module/user_basket_content.html' %}
    </div>
{% endblock %}

user_panel_module/templates/user_panel_module/user_basket_content.html
{% load poll_extras %}

{% if order.order_details.all %}
    <section id="cart_items">
        <div class="container">
            <div class="table-responsive cart_info">
                <table class="table table-condensed">
                    <thead>
                    <tr class="cart_menu">
                        <td class="image">کـالا</td>
                        <td class="description"></td>
                        <td class="price">قیمت</td>
                        <td class="quantity">تعـداد</td>
                        <td class="total">مجمـوع</td>
                        <td></td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for detail in order.order_details.all %}
                        <tr>
                            <td class="cart_product">
                                <a href="{{ detail.product.get_absolute_url }}"><img src="{{ detail.product.image.url }}" width="75" alt="image"></a>
                            </td>
                            <td class="cart_description">
                                <h4><a href="{{ detail.product.get_absolute_url }}" class="one-line-text">{{ detail.product.title }}</a></h4>
                                <p>شناسـه : {{ detail.product.id }}</p>
                            </td>
                            <td class="cart_price">
                                <p>{{ detail.product.price|three_digits_currency }}</p>
                            </td>
                            <td class="cart_quantity">
                                <div class="cart_quantity_button">
                                    <a class="cart_quantity_up cursor-pointer" onclick="changeOrderDetailCount({{ detail.id }}, 'increase')"> + </a>
                                    <input class="cart_quantity_input" type="text" name="quantity" value="{{ detail.count }}" autocomplete="off" size="2">
                                    <a class="cart_quantity_down  cursor-pointer" onclick="changeOrderDetailCount({{ detail.id }}, 'decrease')"> - </a>
                                </div>
                            </td>
                            <td class="cart_total">
                                 <p class="cart_total_price"> {{ detail.get_total_price|three_digits_currency }} </p>
                            </td>
                            <td class="cart_delete">
                                <a class="cart_quantity_delete" onclick="removeOrderDetail({{ detail.id }})"><i class="fa fa-times"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>
    <section id="do_action">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="total_area">
                        <ul>
                            <li>مجمـوع سبـد خریـد <span>{{ sum|three_digits_currency }}</span></li>
                        </ul>
                        <a class="btn btn-default check_out" href="{% url 'orders:request_payment' %}">پرداخت</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% else %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-warning">
                    <p>سبد خرید شما خالی می باشد</p>
                </div>
            </div>
        </div>
    </div>
{% endif %}

user_panel_module/templates/user_panel_module/user_panel_dashboard_page.html
{% extends 'shared/_layout.html' %}
{% load render_partial %}

{% block title %}داشبورد{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                {% render_partial 'user_panel_module.views.user_panel_menu_component' %}
            </div>
            <div class="col-md-8">
                <p>this is user dashboard</p>
            </div>
        </div>
    </div>
{% endblock %}

user_panel_module/templates/user_panel_module/user_shopping.html
{% extends 'shared/_layout.html' %}
{% load render_partial %}
{% load poll_extras %}

{% block title %}لیست خرید های من{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                {% render_partial 'user_panel_module.views.user_panel_menu_component' %}
            </div>
            <div class="col-md-8">
                <table class="table table-responsive table-hover table-striped">
                    <tr>
                        <th class="text-right">شناسه</th>
                        <th class="text-right">تاریخ تایید فاکتور</th>
                        <th class="text-right">قیمت نهایی خرید</th>
                        <th class="text-right">دستورات</th>
                    </tr>
                    {% for order in orders %}
                        <tr>
                            <td class="text-right">{{ order.id }}</td>
                            <td class="text-right"> {{ order.payment_date | show_jalali_date }}</td>
                            <td class="text-right">{{ order.calculate_total_price | three_digits_currency }}</td>
                            <td><a href="{% url 'users:user_shopping_detail_page' order_id=order.id %}" class="btn btn-success">جزییات</a></td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

user_panel_module/templates/user_panel_module/user_shopping_detail.html
{% extends 'shared/_layout.html' %}
{% load render_partial %}
{% load poll_extras %}

{% block title %}جزییات خرید{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                {% render_partial 'user_panel_module.views.user_panel_menu_component' %}
            </div>
            <div class="col-md-8">
                <table class="table table-responsive table-hover table-striped">
                    <tr>
                        <th class="text-right">شناسه</th>
                        <th class="text-right">محصول</th>
                        <th class="text-right">تعداد</th>
                        <th class="text-right">قیمت نهایی خرید</th>
                    </tr>
                    {% for detail in order.order_details.all %}
                        <tr>
                            <td class="text-right">{{ detail.id }}</td>
                            <td class="text-right">{{ detail.product.title }}</td>
                            <td class="text-right">{{ detail.count }}</td>
                            <td class="text-right">{{ detail.final_price|three_digits_currency }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}