account_module/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register_page'),
    path('login/', views.LoginView.as_view(), name='login_page'),
    path('activate-account/<email_active_code>', views.ActivateAccountView.as_view(), name='activate_account'),
    path('logout/', views.LogoutView.as_view(), name='logout_page'),
    path('forget-pass/', views.ForgetPasswordView.as_view(), name='forget_password_page'),
    path('reset-pass/<active_code>', views.ResetPasswordView.as_view(), name='reset_password_page'),
]

article_module/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('list/', views.ArticlesListView.as_view(), name='articles_list'),
    path('list/cat/<str:category>/', views.ArticlesListView.as_view(), name='articles_by_category_list'),
    path('detail/<int:pk>/', views.ArticleDetailView.as_view(), name='articles_detail'),
    path('add-article-comment/', views.add_article_comment, name='add_article_comment'),
]

eshop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home_module.urls', namespace='home')),
    path('accounts/', include('account_module.urls', namespace='accounts')),
    path('articles/', include('article_module.urls', namespace='articles')),
    path('contact_us/', include('contact_module.urls', namespace='contact_us')),
    path('products/', include('product_module.urls', namespace='products')),
    path('users/', include('user_panel_module.urls', namespace='users')),
    path('orders/', include('order_module.urls', namespace='orders')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.sites.AdminSite.site_title = "پنل مدیریت"
admin.sites.AdminSite.site_header = "پنل مدیریت"
admin.sites.AdminSite.index_title = "پنل مدیریت"

home_module/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home_page'),
    path('about-us/', views.AboutView.as_view(), name='about_page'),
]

article_module/models.py
from django.db import models
from jalali_date import date2jalali, datetime2jalali
from account_module.models import User


class ArticleCategory(models.Model):
    parent = models.ForeignKey('ArticleCategory', on_delete=models.CASCADE, related_name='categories', blank=True, null=True, verbose_name='دسته بندی والد')
    title = models.CharField(max_length=200, verbose_name='عنوان دسته بندی')
    url_title = models.CharField(max_length=200, unique=True, verbose_name='عنوان در url')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی مقاله'
        verbose_name_plural = 'دسته بندی های مقاله'


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='articles', blank=True, null=True, verbose_name='نویسنده')
    categories = models.ManyToManyField(ArticleCategory, related_name='articles', verbose_name='دسته بندی ها')
    title = models.CharField(max_length=500, verbose_name='عنوان مقاله')
    slug = models.SlugField(max_length=500, allow_unicode=True, verbose_name='عنوان در url')
    short_description = models.TextField(max_length=500, verbose_name='توضیحات کوتاه')
    text = models.TextField(max_length=5000, verbose_name='متن مقاله')
    image = models.ImageField(upload_to='images/articles', verbose_name='تصویر مقاله')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')

    class Meta:
        ordering = ['-create_date']
        indexes = [
            models.Index(fields=['slug']),
            models.Index(fields=['-create_date']),
        ]
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'

    def __str__(self):
        return self.title

    def get_jalali_date(self):
        return date2jalali(self.create_date)

    def get_jalali_time(self):
        return datetime2jalali(self.create_date).strftime('%H:%M')


class ArticleComment(models.Model):
    parent = models.ForeignKey('ArticleComment', on_delete=models.CASCADE, related_name='comments', blank=True, null=True, verbose_name='والد')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments', verbose_name='مقاله')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments', verbose_name='کاربر')
    text = models.TextField(max_length=1000, verbose_name='متن نظر')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')

    def __str__(self):
        return f'{self.text}'

    class Meta:
        verbose_name = 'نظر مقاله'
        verbose_name_plural = 'نظرات مقاله'

article_module/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import DetailView
from django.views.generic.list import ListView
from article_module.models import Article, ArticleCategory, ArticleComment


class ArticlesListView(ListView):
    model = Article
    template_name = 'article_module/articles_page.html'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super(ArticlesListView, self).get_context_data()
        return context

    def get_queryset(self):
        query = super(ArticlesListView, self).get_queryset()
        query = query.filter(is_active=True)
        category_name = self.kwargs.get('category')
        if category_name is not None:
            query = query.filter(categories__url_title__iexact=category_name)
        return query


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article_module/article_detail_page.html'

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data()
        article: Article = kwargs.get('object')
        context['comments'] = ArticleComment.objects.filter(article_id=article.id, parent=None).order_by('-create_date').prefetch_related('comments')
        context['comments_count'] = ArticleComment.objects.filter(article_id=article.id).count()
        return context

    def get_queryset(self):
        query = super(ArticleDetailView, self).get_queryset()
        query = query.filter(is_active=True)
        return query


@login_required
def add_article_comment(request: HttpRequest):
    if request.user.is_authenticated:
        article_id = request.GET.get('article_id')
        article_comment = request.GET.get('article_comment')
        parent_id = request.GET.get('parent_id')
        print(article_id, article_comment, parent_id)
        ArticleComment.objects.create(article_id=article_id, text=article_comment, user_id=request.user.id, parent_id=parent_id)
        context = {
            'comments': ArticleComment.objects.filter(article_id=article_id, parent=None).order_by('-create_date').prefetch_related('comments'),
            'comments_count': ArticleComment.objects.filter(article_id=article_id).count(),
        }
        return render(request, 'article_module/includes/article_comments_partial.html', context)
    return HttpResponse('response')


def article_categories_component(request: HttpRequest):
    article_main_categories = ArticleCategory.objects.prefetch_related('categories').filter(is_active=True, parent_id=None)
    context = {'main_categories': article_main_categories}
    return render(request, 'article_module/components/article_categories_component.html', context)

article_module/templates/article_module/article_detail_page.html
{% extends 'shared/_layout.html' %}
{% load render_partial %}
{% load poll_extras %}
{% load thumbnail %}

{% block title %}جزییات مقاله{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="blog-post-area">
                        <h2 class="title text-center">{{ article.title }}</h2>
                        <div class="single-blog-post">
                            <h3>{{ article.title }}</h3>
                            <div class="post-meta">
                                <ul>
                                    {% if article.author %}
                                        <li><i class="fa fa-user"></i> {{ article.author }}</li>
                                    {% endif %}
                                    <li><i class="fa fa-clock-o"></i>{{ article.create_date | show_jalali_time }}</li>
                                    <li><i class="fa fa-calendar"></i>{{ article.create_date | show_jalali_date }}</li>
                                </ul>
                                <span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
                            </div>
                            <a href="#">
                                {% thumbnail article.image "862x398" quality=95 crop='center' as im %}
                                    <img src="{{ im.url }}">
                                {% endthumbnail %}
                            </a>
                            <p>{{ article.short_description }} </p>
                            <p>{{ article.text }}</p>
                        </div>
                    </div>
                    {% if article.author %}
                        <div class="media commnets">
                            <a class="pull-right" href="#">
                                {% if article.author.avatar %}
                                    {% thumbnail article.author.avatar "121x86" quality=95 crop='center' as im %}
                                        <img class="media-object" src="{{ im.url }}">
                                    {% endthumbnail %}
                                {% else %}
                                    <img class="media-object" src="/static/images/blog/Customer.jpg" alt="">
                                {% endif %}
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading">نویسنده : {{ article.author }}</h4>
                                <p>{{ article.author.about_user }}</p>
                            </div>
                        </div>
                    {% endif %}
                    <div class="response-area" id="comments_area">
                        <h2> نظرات ({{ comments_count }})</h2>
                        <ul class="media-list">
                            {% for comment in comments %}
                                <li class="media" id="single_comment_box_{{ comment.id }}">
                                    <a class="pull-right" href="#">
                                        {% if comment.user.avatar %}
                                            {% thumbnail comment.user.avatar "121x86" quality=95 crop='center' as im %}
                                                <img class="media-object" src="{{ im.url }}">
                                            {% endthumbnail %}
                                        {% else %}
                                            <img class="media-object" src="/static/images/blog/Customer.jpg" alt="">
                                        {% endif %}
                                    </a>
                                    <div class="media-body">
                                        <ul class="sinlge-post-meta">
                                            <li><i class="fa fa-user"></i>{{ comment.user }}</li>
                                            <li><i class="fa fa-clock-o"></i> {{ comment.create_date | show_jalali_time }}</li>
                                            <li><i class="fa fa-calendar"></i> {{ comment.create_date | show_jalali_date }}</li>
                                        </ul>
                                        <p>{{ comment.text }}</p>
                                        <a class="btn btn-primary" onclick="fillParentId({{ comment.id }})"><i class="fa fa-reply"></i>پاسـخ</a>
                                    </div>
                                </li>
                                {% for sub_comment in comment.comments.all %}
                                    <li class="media second-media" id="single_comment_box_{{ comment.id }}">
                                        <a class="pull-right" href="#">
                                            {% if sub_comment.user.avatar %}
                                                {% thumbnail sub_comment.user.avatar "121x86" quality=95 crop='center' as im %}
                                                    <img class="media-object" src="{{ im.url }}">
                                                {% endthumbnail %}
                                            {% else %}
                                                <img class="media-object" src="/static/images/blog/Customer.jpg" alt="">
                                            {% endif %}
                                        </a>
                                        <div class="media-body">
                                            <ul class="sinlge-post-meta">
                                                <li><i class="fa fa-user"></i>{{ sub_comment.user }}</li>
                                                <li><i class="fa fa-clock-o"></i> {{ sub_comment.create_date | show_jalali_time }}</li>
                                                <li><i class="fa fa-calendar"></i> {{ sub_comment.create_date | show_jalali_date }}</li>
                                            </ul>
                                            <p>{{ sub_comment.text }}</p>
                                        </div>
                                    </li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="replay-box" id="comment_form">
                        {% if request.user.is_authenticated %}
                            <div class="row">
                                <div class="col-sm-12">
                                    <h2>نظـر خود را بنویسیـد</h2>
                                    <div class="text-area">
                                        <input type="hidden" id="parent_id" value="">
                                        <div class="blank-arrow"><label>متن پیام</label></div>
                                        <span>*</span>
                                        <textarea name="message" rows="11" id="commentText"></textarea>
                                        <a class="btn btn-primary" onclick="sendArticleComment({{ article.id }})">ارسـال نظـر</a>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="alert alert-warning">برای درج نظر می بایست <a href="{% url 'accounts:login_page' %}">لاگین</a> کنید</div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="left-sidebar">
                        {% render_partial 'article_module.views.article_categories_component' %}
{#                        <div class="shipping text-center">#}
{#                            <img src="/static/images/home/shipping.jpg" alt="">#}
{#                        </div>#}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

article_module/templates/article_module/articles_page.html
{% extends 'shared/_layout.html' %}
{% load poll_extras %}
{% load thumbnail %}
{% load render_partial %}

{% block title %}لیست مقالات{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="blog-post-area">
                        <h2 class="title text-center">آخریـن اخبـار</h2>
                        {% for article in object_list %}
                            <div class="single-blog-post">
                                <h3>{{ article.title }}</h3>
                                <div class="post-meta">
                                    <ul>
                                        {% if article.author %}
                                            <li><i class="fa fa-user"></i> {{ article.author }}</li>
                                        {% endif %}
                                        <li><i class="fa fa-clock-o"></i>{{ article.create_date | show_jalali_time }}</li>
                                        <li><i class="fa fa-calendar"></i>{{ article.create_date | show_jalali_date }}</li>
                                    </ul>
                                    <span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								    </span>
                                </div>
                                <a href="{% url 'articles:articles_detail' pk=article.id %}">
                                    {% thumbnail article.image "862x398" quality=95 crop='center' as im %}
                                        <img src="{{ im.url }}" alt="{{ im.name }}">
                                    {% endthumbnail %}
                                </a>
                                <p>{{ article.short_description }}</p>
                                <a class="btn btn-primary" href="{% url 'articles:articles_detail' pk=article.id %}">ادامـه مطلب</a>
                            </div>
                        {% endfor %}
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                            {% endif %}
                            {% for pageNumber in paginator.page_range %}
                                <li class="{% if page_obj.number == pageNumber %} active {% endif %}">
                                    <a href="?page={{ pageNumber }}">{{ pageNumber }}</a>
                                </li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="left-sidebar">
                        {% render_partial 'article_module.views.article_categories_component' %}
{#                        <div class="shipping text-center">#}
{#                            <img src="/static/images/home/shipping.jpg" alt="">#}
{#                        </div>#}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}